name       : file-roller
version    : 3.24.1
release    : 23
source     :
    - https://download.gnome.org/sources/file-roller/3.24/file-roller-3.24.1.tar.xz : 011545e8bd81a415fb068718347bf63ced4ab176210ce36a668904a3124c7f3a
license    : GPL-2.0+
summary    : Archive manager for the GNOME desktop environment
description: |
    File Roller is an archive manager for the GNOME desktop environment
component  : desktop.gnome
builddeps  :
    - itstool
    - pkgconfig(gtk+-3.0)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libarchive)
    - pkgconfig(libnautilus-extension)
    - pkgconfig(libnotify)
rundeps    :
    - unrar
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
