name        : file-roller
version     : 3.16.2
release     : 10
source     :
    - http://ftp.gnome.org/pub/gnome/sources/file-roller/3.16/file-roller-3.16.2.tar.xz : 60897ff24d4822395a227b62811c3b8768b701844961e93303d6d6d9463d7e3f
license     : GPL-2.0+
summary     : Archive manager for the GNOME desktop environment
builddeps   :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libnautilus-extension)
    - pkgconfig(libarchive)
    - pkgconfig(libnotify)
    - pkgconfig(json-glib-1.0)
    - itstool
description : |
    File Roller is an archive manager for the GNOME desktop environment
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
