name       : file-roller
version    : '43.0'
release    : 40
source     :
    - https://download.gnome.org/sources/file-roller/43/file-roller-43.0.tar.xz : 298729fdbdb9da8132c0bbc60907517d65685b05618ae05167335e6484f573a1
license    : GPL-2.0-or-later
summary    : Archive manager for the GNOME desktop environment
description: |
    File Roller is an archive manager for the GNOME desktop environment
component  : desktop.gnome
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libarchive)
    - pkgconfig(libhandy-1)
    - pkgconfig(libportal)
    - pkgconfig(libnautilus-extension-4)
    - desktop-file-utils
    - itstool
rundeps    :
    - unrar
setup      : |
    %meson_configure -Dpackagekit=false
build      : |
    %ninja_build
install    : |
    %ninja_install
