name       : file-roller
version    : 3.42.0
release    : 39
source     :
    - https://download.gnome.org/sources/file-roller/3.42/file-roller-3.42.0.tar.xz : 1c438e6d53ec10ff4f2eb5b22d7bbf28a7c2a84957ab64a751c1cdf3c52302c7
license    : GPL-2.0-or-later
summary    : Archive manager for the GNOME desktop environment
description: |
    File Roller is an archive manager for the GNOME desktop environment
component  : desktop.gnome
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libarchive)
    - pkgconfig(libhandy-1)
    - pkgconfig(libnautilus-extension)
    - pkgconfig(libnotify)
    - itstool
rundeps    :
    - unrar
setup      : |
    %meson_configure -Dpackagekit=false
build      : |
    %ninja_build
install    : |
    %ninja_install
