name       : file-roller
version    : 3.28.1
release    : 29
source     :
    - https://download.gnome.org/sources/file-roller/3.28/file-roller-3.28.1.tar.xz : 574b084eaac142357f54419f8406b029038059845eb16b05eb8e314d2b5dc227
license    : GPL-2.0-or-later
summary    : Archive manager for the GNOME desktop environment
description: |
    File Roller is an archive manager for the GNOME desktop environment
component  : desktop.gnome
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libarchive)
    - pkgconfig(libnautilus-extension)
    - pkgconfig(libnotify)
    - itstool
rundeps    :
    - unrar
setup      : |
    %meson_configure -Dpackagekit=false
build      : |
    %ninja_build
install    : |
    %ninja_install
