name       : file-roller
version    : 3.38.1
release    : 34
source     :
    - https://download.gnome.org/sources/file-roller/3.38/file-roller-3.38.1.tar.xz : 94a0130e12d321aa119793a14d09716523e2e4a61f29570cee53fd88dd6abc57
license    : GPL-2.0-or-later
summary    : Archive manager for the GNOME desktop environment
description: |
    File Roller is an archive manager for the GNOME desktop environment
component  : desktop.gnome
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libarchive)
    - pkgconfig(libnautilus-extension)
    - pkgconfig(libnotify)
    - itstool
rundeps    :
    - unrar
setup      : |
    %meson_configure -Dpackagekit=false
build      : |
    %ninja_build
install    : |
    %ninja_install
