name        : file-roller
version     : 3.16.4
release     : 14
source     :
    - http://ftp.gnome.org/pub/gnome/sources/file-roller/3.16/file-roller-3.16.4.tar.xz : 5455980b2c9c7eb063d2d65560ae7ab2e7f01b208ea3947e151680231c7a4185
license     : GPL-2.0+
summary     : Archive manager for the GNOME desktop environment
builddeps   :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libnautilus-extension)
    - pkgconfig(libarchive)
    - pkgconfig(libnotify)
    - pkgconfig(json-glib-1.0)
    - itstool
rundeps     :
    - unrar
description : |
    File Roller is an archive manager for the GNOME desktop environment
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
