name       : file-roller
version    : 3.22.3
release    : 21
source     :
    - http://ftp.gnome.org/pub/gnome/sources/file-roller/3.22/file-roller-3.22.3.tar.xz : de858640632a0e22769b6b73d5b98527f3cfc2c83f99692063e352e41d533505
license    : GPL-2.0+
summary    : Archive manager for the GNOME desktop environment
description: |
    File Roller is an archive manager for the GNOME desktop environment
component  : desktop.gnome
builddeps  :
    - itstool
    - pkgconfig(gtk+-3.0)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libarchive)
    - pkgconfig(libnautilus-extension)
    - pkgconfig(libnotify)
rundeps    :
    - unrar
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
